use_frameworks!

#source 'https://github.com/caodakeng/repo.git'
#source 'https://github.com/CocoaPods/Specs.git' # cocoapods 公用仓库地址

platform :ios, '8.0'

target 'cx_demo_Example' do
  pod 'cx_demo', :path => '../'
#  pod 'cx_demo'
#  pod 'SDWebImage'
  
  
  target 'cx_demo_Tests' do
    inherit! :search_paths

    
  end
end
